# 服务端口
server:
  port: 8304

spring:
  application:
    # 服务名
    name: service-user

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: '010111'

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

  #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

#公众号id和秘钥
# 硅谷课堂微信公众平台appId
wechat:
  mpAppId: wxd1e7a6e9e1594b61
  ## 硅谷课堂微信公众平台api秘钥
  mpAppSecret: a3f8dab1bb994c01557c76f57430ecb6
  # 授权回调获取用户信息接口地址
  userInfoUrl: https://4e31i36306.yicp.fun/api/user/wechat/userInfo


